let pageConfig = {};
pageConfig.basket = {
  name: "basket",
  form: {
    schema: {
      title: "Cấu hình hệ thống",
      type: "object",
      properties: {
        id: {
          title: "ID",
          modelSelectField: "id,name",
          classNames: "col-md-12",
          type: "number",
          required: false,
        },
        key: {
          title: "Khóa",
          modelSelectField: "id,name",
          classNames: "col-md-12",
          type: "string",
        },
        type: {
          title: "Kiểu dữ liệu",
          type: "integer",
          modelSelectField: "id,name",
          classNames: "col-md-12",
          required: false,
          items: [
            {
              key: "Số",
              value: "1",
            },
            {
              key: "Chuỗi",
              value: "2",
            },
          ],
        },
        val: {
          title: "Giá trị",
          modelSelectField: "id,name",
          classNames: "col-md-12",
        },
        desc: {
          title: "Mô tả",
          modelSelectField: "id,name",
          classNames: "col-md-12",
          type: "string",
        },
      },
      required: [],
    },
    uiSchema: {
      id: {
        "ui:disabled": false,
      },
      key: {
        "ui:widget": "text",
      },
      type: {
        "ui:widget": "EnumWidget",
      },
      desc: {
        "ui:widget": "textarea",
      },
    },
  },
  schema: [
    {
      name: "Name",
      required: true,
      field: "name",
      modelSelectField: "id,name",
      widget: "Text",
      group: "",
      type: "string",
    },
    {
      name: "Key",
      required: true,
      field: "key",
      type: "string",
      modelSelectField: "id,name",
      widget: "Text",
      group: "",
    },
    {
      name: "Data Type",
      required: false,
      field: "type",
      items: [
        {
          key: "String",
          value: "string",
        },
        {
          key: "Number",
          value: "number",
        },
        {
          key: "Boolean",
          value: "boolean",
        },
        {
          key: "Float",
          value: "float",
        },
        {
          key: "Integer",
          value: "integer",
        },
        {
          key: "Array",
          value: "array",
        },
      ],
      type: "string",
      modelSelectField: "id,name",
      widget: "Enum",
      group: "",
    },
    {
      name: "Description",
      required: false,
      field: "desc",
      type: "string",
      modelSelectField: "id,name",
      widget: "TextArea",
      group: "",
    },
    {
      name: "Sub Configs",
      field: "subConfigs",
      type: "json",
      widget: "TableGenerate",
      items: [
        {
          title: "Sub Code",
          dataType: "string",
          field: "subCode",
          interfaceType: "Text",
          placeholder: "Sub Code",
        },
        {
          title: "Name",
          dataType: "string",
          field: "name",
          interfaceType: "Text",
          placeholder: "Name",
        },
        {
          title: "Key/ Value",
          dataType: "string",
          field: "value",
          interfaceType: "Text",
          placeholder: "Key/ Value",
        },
        {
          title: "Type",
          dataType: "string",
          field: "type",
          interfaceType: "SelectModel",
          placeholder: "",
        },
      ],
      group: "",
    },
  ],
  buttons: [
    {
      type: "button",
      title: "Edit",
      color: "warning",
      mode: "edited",
      icon: "fa fa-pencil",
      backOnDone: false,
      api: "find_one_config",
      action: "formModal",
      url: "",
      modalQuery: '{"page":"1080070560928390","mode":"edit","sid":#sid#}',
      apiBasic: true,
    },
    {
      type: "submit",
      title: "Create",
      color: "success",
      mode: "created",
      icon: "fa fa-plus",
      backOnDone: false,
      api: "create",
      action: "formModal",
      url: "#/form?page=5e07162b8b58f4bc1d4804ee&mode=create",
      modalQuery: '{"page":"1080070560928390","mode":"create"}',
      onViewScreen: true,
    },
    {
      mode: "create",
      title: "Create Config",
      color: "success",
      icon: "fa fa-check",
      type: "switch",
      action: "api",
      api: "create",
    },
    {
      mode: "edit",
      title: "Update Config",
      color: "primary",
      icon: "fa fa-check",
      apiBasic: true,
      api: "update",
      type: "switch",
      action: "api",
      confirm: "Are you want to update?",
    },
    {
      mode: "destroy",
      title: "Delete",
      color: "danger",
      icon: "fa fa-trash",
      type: "button",
      confirm: "Are you want to destroy?",
      api: "destroy",
      action: "api",
    },
  ],

  roles: ["5e07162b8b58f4bc1d4804f3"],
  apis: [
    {
      method: "POST",
      name: "findALl",
      url: "/api/basket/getallbasket",
      requestFields: "",
      responseFields: "",
      type: "find",
    },
    {
      name: "create",
      url: "/api/basket/create",
      type: "create",
      method: "POST",
      sid: "4794360057",
      title: "Create Config",
    },
  ],
  grid: [
    {
      name: "SID",
      type: "number",
      field: "sid",
      filterable: true,
      enumable: false,
    },
    {
      name: "Key",
      type: "string",
      field: "key",
      filterable: true,
    },
    {
      name: "Name",
      field: "name",
      type: "string",
      filterable: true,
    },
    {
      name: "Data Type",
      type: "string",
      field: "type",
      enumable: false,
      items: [],
      filterable: true,
    },
    {
      name: "Description",
      type: "string",
      field: "desc",
      filterable: true,
    },
    {
      name: "Created At",
      type: "date",
      field: "createdAt",
    },
    {
      name: "Edited At",
      type: "date",
      field: "updatedAt",
    },
    {
      name: "Last edit by",
      field: "updatedBy.name",
      type: "string",
      filterable: true,
    },
  ],
};
